package notificaties.zendnotificatie.constants

import rego.v1

event_types := {
	"UZOVI": {
		"OVERDRACHT_ZORGKANTOOR",
		"NIEUWE_BEMIDDELINGSPECIFICATIE_ZORGKANTOOR",
		"NIEUWE_OVERDRACHT_ZORGKANTOOR",
		"NIEUWE_INDICATIE_ZORGKANTOOR",
		"GEWIJZIGDE_BEMIDDELINGSPECIFICATIE_ZORGKANTOOR",
		"GEWIJZIGDE_OVERDRACHT_ZORGKANTOOR",
		"VERWIJDERDE_BEMIDDELINGSPECIFICATIE_ZORGKANTOOR",
		"VERWIJDERDE_OVERDRACHT_ZORGKANTOOR",
		"VERVALLEN_INDICATIE_ZORGKANTOOR",
		"iWLZFOUTMELDING",
		"IWLZFOUTMELDING",
	},
	"AGB": {
		"NIEUWE_BEMIDDELINGSPECIFICATIE_ZORGAANBIEDER",
		"NIEUWE_REGIEHOUDER_ZORGAANBIEDER",
		"GEWIJZIGDE_BEMIDDELINGSPECIFICATIE_ZORGAANBIEDER",
		"GEWIJZIGDE_ZORGSAMENSTELLING_ZORGAANBIEDER",
		"GEWIJZIGDE_REGIEHOUDER_ZORGAANBIEDER",
		"VERWIJDERDE_BEMIDDELINGSPECIFICATIE_ZORGAANBIEDER",
		"VERWIJDERDE_REGIEHOUDER_ZORGAANBIEDER",
		"BEEINDIGDE_ROL_COORDINATORZORGTHUIS_ZORGAANBIEDER",
		"BEEINDIGDE_ROL_DOSSIERHOUDER_ZORGAANBIEDER",
		"ROL_COORDINATORZORGTHUIS_ZORGAANBIEDER",
		"ROL_DOSSIERHOUDER_ZORGAANBIEDER",
		"INFORMATIEVE_BEMIDDELINGSPECIFICATIE_ZORGAANBIEDER",
	},
	"KVK": {"MUTATIE_CLIENT"},
}
